theme = "nord"

[keys.normal]
C-a = "select_all"                 
C-c = "yank_to_clipboard"   
C-z = "undo"  
C-f = "search"
C-q = ":q!"
C-s = ":w"
C-t = "goto_window_top"
C-o = ":open /home/michael/nixos-build/dotfiles/config/helix/config.toml"
C-right = "move_next_word_start"

[keys.insert]    
C-a = "select_all"             
C-c = "yank_to_clipboard"     
C-z = "undo"   
C-f = "search"
C-q = ":q!"  
C-s = ":w"
C-t = "goto_window_top"
C-right = "move_next_word_start"


#remapping = https://docs.helix-editor.com/remapping.html


