[language-server.gopls]
command = "gopls"

[[language]]
name = "go"
auto-format = true
language-servers = [ 
    { name = "gopls", only-features = [ 
        "format", "completion", "diagnostics", "inlay-hints"
    ] }, 
    "typescript-language-server" 
    ]

file-types = [ "go" ]
diagnostic-severity = "Error" 

[editor.lsp]
auto-signature-help = false
signature-help = false


