attribute = "white"
keyword = "nord_lilac"
"keyword.directive" = "nord_lilac" # -- preprocessor comments (#if in C)
namespace = "white"
punctuation = "nord_orange"
"punctuation.delimiter" = "nord_lilac"
operator = "nord_lilac"
special = "nord_orange"
"variable.other.member" = "white"
variable = "white"
# variable = "almond" # TODO: metavariables only
# "variable.parameter" = { fg = "nord_lilac", modifiers = ["underlined"] }
"variable.parameter" = { fg = "white" }
"variable.builtin" = "nord_light_blue"
type = "white"
"type.builtin" = "white" # TODO: distinguish?
constructor = "nord_green"
function = "nord_green"
"function.macro" = "nord_light_blue"
"function.builtin" = "white"
tag = "white"
comment = "nord_dark"
constant = "white"
"constant.builtin" = "white"
string = "nord_blue"
"constant.numeric" = "chamois"
"constant.character.escape" = "honey"
# used for lifetimes
label = "nord_orange"

"markup.heading" = "nord_blue"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "nord_green", modifiers = ["underlined"] }
"markup.link.text" = "almond"
"markup.raw" = "almond"

"diff.plus" = "nord_green"
"diff.minus" = "nord_red"
"diff.delta" = "nord_yellow"

# TODO: diferentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background" = { fg = "nord_lilac" }
"ui.background.separator" = { fg = "nord_blue" }
"ui.linenr" = { fg = "nord_midnight" }
"ui.linenr.selected" = { fg = "nord_lilac" }
"ui.statusline" = { fg = "nord_lilac", bg = "nord_midnight" }
"ui.statusline.inactive" = { fg = "nord_lilac"}
"ui.popup" = { bg = "nord_blue" }
"ui.window" = { fg = "nord_midnight" }
"ui.help" = { bg = "nord_midnight", fg = "white" }

"ui.text" = { fg = "white" }
"ui.text.focus" = { fg = "white" }
"ui.text.inactive" = "nord_orange"
"ui.virtual" = { fg = "nord_midnight" }

"ui.virtual.indent-guide" = { fg = "nord_midnight" }

"ui.selection" = { bg = "#540099" }
"ui.selection.primary" = { bg = "nord_midnight" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor.select" = { bg = "white" }
"ui.cursor.insert" = { bg = "white" }
"ui.cursor.match" = { fg = "white", bg = "nord_midnight" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "nord_midnight" }
"ui.highlight" = { bg = "white" }
"ui.highlight.frameline" = { bg = "white" }
"ui.debug" = { fg = "#nord_blue" }
"ui.debug.breakpoint" = { fg = "nord_orange" }
"ui.menu" = { fg = "nord_lilac" }
"ui.menu.selected" = { fg = "nord_blue", bg = "white" }
"ui.menu.scroll" = { fg = "nord_lilac", bg = "nord_midnight" }

"diagnostic.hint" = { underline = { color = "nord_green", style = "curl" } }
"diagnostic.info" = { underline = { color = "nord_light_blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "nord_yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "nord_red", style = "curl" } }

warning = "nord_yellow"
error = "nord_red"
info = "nord_light_blue"
hint = "nord_green"

[palette]
white = "#ebe5e5"

nord_lilac = "#B48EAD"
nord_midnight = "#3B4252"
nord_dark = "#4C566A"

nord_green = "#8FBCBB"
nord_green_dark = "#A3BE8C"
nord_blue = "#81A1C1"
nord_orange = "#D08770"

nord_light_blue = "#88C0D0"
nord_yellow = "#EBCB8B"
nord_red = "#BF616A"



comet = "#5a5977"
bossanova = "#452859"

revolver = "#281733"

sirocco = "#697C81"
almond = "#eccdba"
chamois = "#E8DCA0"
honey = "#efba5d"

apricot = "#f47868"
lightning = "#ffcd1c"
delta = "#6F44F0"